apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: spring-boot-postgres
spec:
  ports:
    - port: 3306
  selector:
    app: spring-boot-postgres
    tier: postgres
  clusterIP: None